### ISSUE TITLE
Anyone still working on mephisto?

### ISSUE THREAD

**Issue by kingsleyh** [mephistorb/mephisto#1]
Hi - is anyone still developing mephisto - if so - let me know - as I'm interested.

Thanks

--K

**Comment by hooptie45** [comment]
I just found this project, and I'd be happy to jump on board

**Comment by kingsleyh** [comment]
Great :) I'm free in August

**Comment by halorgium** [comment]
Maybe I should move this to an organization. 
I never actually hacked on it, just mirrored the repo. :tophat:
